# Generated by Django 5.2 on 2025-05-08 13:14

from django.db import migrations

def create_waste_types(apps, schema_editor):
    Waste = apps.get_model('api', 'Waste')
    waste_types = ['PLASTIC', 'PAPER', 'GLASS', 'METAL']
    for waste_type in waste_types:
        Waste.objects.create(type=waste_type)

def delete_waste_types(apps, schema_editor):
    Waste = apps.get_model('api', 'Waste')
    Waste.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_waste_userwastes'),
    ]

    operations = [
        migrations.RunPython(create_waste_types, delete_waste_types),
    ]
