# Generated by Django 5.2 on 2025-04-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="user",
            table="Users",
        ),
    ]
