# Generated by Django 5.2 on 2025-05-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
