# Generated by Django 5.2 on 2025-05-12 10:20

from django.db import migrations, models


def create_initial_tips(apps, schema_editor):
    """
    Create initial tips for the application
    """
    Tips = apps.get_model('api', 'Tips')
    
    initial_tips = [
        {
            'title': 'Reusable Shopping Bags',
            'text': 'Bring your own reusable bags when shopping to reduce plastic waste. Keep them in your car or by the door so you don\'t forget them!',
            'like_count': 42,
            'dislike_count': 2
        },
        {
            'title': 'Water Conservation',
            'text': 'Turn off the tap while brushing your teeth. This simple action can save up to 8 gallons of water per day!',
            'like_count': 38,
            'dislike_count': 1
        },
        {
            'title': 'Food Waste Reduction',
            'text': 'Plan your meals and make a shopping list to avoid buying more food than you need. Compost fruit and vegetable scraps instead of throwing them away.',
            'like_count': 56,
            'dislike_count': 3
        },
        {
            'title': 'Energy Saving',
            'text': 'Unplug electronics when not in use. Even when turned off, many devices continue to draw power in standby mode.',
            'like_count': 29,
            'dislike_count': 4
        },
        {
            'title': 'Plastic-Free Alternatives',
            'text': 'Use a reusable water bottle instead of buying plastic bottles. Consider bamboo toothbrushes, metal straws, and beeswax wraps as sustainable alternatives.',
            'like_count': 65,
            'dislike_count': 2
        },
        {
            'title': 'Sustainable Transportation',
            'text': 'Whenever possible, walk, bike, or use public transportation to reduce carbon emissions.',
            'like_count': 47,
            'dislike_count': 8
        },
        {
            'title': 'Clothing Recycling',
            'text': 'Donate clothes you no longer wear instead of throwing them away. Consider buying second-hand or from sustainable brands.',
            'like_count': 53,
            'dislike_count': 5
        }
    ]
    
    for tip_data in initial_tips:
        Tips.objects.create(**tip_data)


def remove_initial_tips(apps, schema_editor):
    """
    Remove initial tips if migration is reversed
    """
    Tips = apps.get_model('api', 'Tips')
    Tips.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(create_initial_tips, remove_initial_tips),
    ]
