# Generated by Django 5.2 on 2025-05-14 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_users_total_co2_users_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TipLikes',
                'unique_together': {('user', 'tip')},
            },
        ),
    ]
