# Generated by Django 5.2 on 2025-10-18 09:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tiplikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as2_json', models.JSONField()),
                ('actor_id', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('community_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers', 'Followers'), ('direct', 'Direct')], db_index=True, default='public', max_length=16)),
                ('summary', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'activity_event',
                'indexes': [models.Index(fields=['actor_id', 'published_at'], name='idx_actor_ts'), models.Index(fields=['community_id', 'published_at'], name='idx_comm_ts'), models.Index(fields=['type', 'published_at'], name='idx_type_ts'), models.Index(fields=['object_type', 'object_id'], name='idx_obj_pair'), models.Index(fields=['visibility', 'published_at'], name='idx_vis_ts')],
            },
        ),
    ]
