# Generated by Django 5.2 on 2025-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_activityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tips',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10, null=True),
        ),
    ]
