# Generated by Django 5.2 on 2025-11-18 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(upload_to='suspicious_waste_photos/')),
            ],
            options={
                'db_table': 'SuspiciousWaste',
                'ordering': ['-amount'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddField(
            model_name='suspiciouswaste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciouswaste',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.waste'),
        ),
    ]
