# Generated by Django 5.2 on 2025-11-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_posts_language_alter_tips_language'),
        ('api', '0014_suspiciouswaste_remove_follow_unique_follow_and_more'),
    ]

    operations = [
    ]
