# Generated by Django 5.2 on 2025-12-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20251124_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PLASTIC', 'Plastic'), ('PAPER', 'Paper'), ('GLASS', 'Glass'), ('METAL', 'Metal'), ('ELECTRONIC', 'Electronic'), ('OIL&FATS', 'Oil & Fats'), ('ORGANIC', 'Organic'), ('TOTAL_WASTE', 'Total Waste'), ('CONTRIBUTIONS', 'Contributions'), ('LIKES_RECEIVED', 'Likes Received')], help_text='Badge category (waste type, total waste, contributions, or likes)', max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum'), (5, 'Diamond')], help_text='Achievement level within the category (1-5)')),
                ('criteria_value', models.FloatField(help_text='Required value to earn this badge (grams for waste, count for others)')),
            ],
            options={
                'db_table': 'Badges',
                'ordering': ['category', 'level'],
                'unique_together': {('category', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.badges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserBadges',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
