# Generated by Django 5.2 on 2025-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_badges_userbadges'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers', 'Followers')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='users',
            name='waste_stats_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers', 'Followers')], default='public', max_length=16),
        ),
    ]

