# Generated by Django 5.2 on 2025-12-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_users_profile_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField()),
                ('delete_after', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountDeletionRequest',
            },
        ),
    ]

