# Generated by Django 5.2 on 2025-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_account_deletion_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='anonymous_identifier',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]

