# Generated by Django 5.2 on 2025-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_users_anonymity'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='cancel_token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]

