"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--r&m3rfr3av2!+7x%vy32+pv%$r#$du@#mogm&51*0zktjt!1p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["134.209.253.215", "localhost", '134-209-253-215.sslip.io', '127.0.0.1', '10.0.2.2', "209.38.114.201", "209-38-114-201.sslip.io"]


# Application definition

INSTALLED_APPS = [
    
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "api.apps.ApiConfig", 
    'challenges',
    'carbon',
    'django.contrib.auth',
    'django.contrib.admin',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    "django_filters",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# This is for only development purposes, remove it in production
"""CORS_ALLOWED_ORIGINS = [
    "https://zero-waste-jyr8r0680-basars-projects-58c905f6.vercel.app",
    "http://134.209.253.215:8000",
]
"""
CORS_ALLOW_ALL_ORIGINS = True

CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

AUTH_USER_MODEL = 'api.Users'

ROOT_URLCONF = 'project.urls'

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    "NON_FIELD_ERRORS_KEY": "errors",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 60,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=36500),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=36500),
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'main_db',
        'USER': 'root',
        'PASSWORD': '123456789',
        'HOST': 'backend-db-1',  
        'PORT': '3306',       
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }


# Carbon emission factors (real values)
# Local “Climatiq-style” emission factors (kg CO2e per kg or per item)
# Highly reliable global-average landfill emission factors (kg CO2e per kg)
LOCAL_EMISSION_FACTORS = {
    # Plastic – inert in landfill; modern estimates: 0.009–0.033 kg/kg (DEFRA 2024, ADEME)
    "waste-type_plastics-disposal_method_landfill": 0.02,

    # Paper & cardboard – high methane generation; ~1.1–1.6 kg/kg (DEFRA 2025, EPA WARM)
    "waste_type_paper_and_cardboard-disposal_method_landfill": 1.16,

    # Glass – inert; ~0.009 kg/kg (DEFRA 2024 landfill factor)
    "waste-type_glass-disposal_method_landfilled": 0.009,

    # Metal (steel cans) – inert; ~0.009 kg/kg (DEFRA 2024)
    "waste_type_scrap_metal_steel_cans-disposal_method_landfill": 0.009,

    # Electronics (mixed WEEE) – inert unless containing refrigerants; ~0.021 kg/kg (DEFRA 2024)
    "waste-type_weee_mixed-disposal_method_landfill": 0.021,

    # Used vegetable cooking oil purification – LCA-based (Ecoinvent v3): ~1.1 kg/kg
    "waste_management-type_used_vegetable_cooking_oil_purified_treatment_of_used_vegetable_cooking_oil_purification-disposal_method_na": 1.10,

    # Organic food & garden waste – high methane; ~0.656 kg/kg (DEFRA 2024)
    "waste-type_mixed_food_and_organic_garden-disposal_method_landfill": 0.656,
}


CARBON_DECIMALS = 6