# Generated by Django 5.2 on 2025-05-08 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLASTIC', 'Plastic'), ('PAPER', 'Paper'), ('GLASS', 'Glass'), ('METAL', 'Metal')], max_length=50)),
            ],
            options={
                'db_table': 'Waste',
            },
        ),
        migrations.CreateModel(
            name='UserWastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.waste')),
            ],
            options={
                'db_table': 'UserWastes',
                'ordering': ['-date'],
            },
        ),
    ]
