# Generated by Django 5.2 on 2025-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_savedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_co2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
