# Generated by Django 5.2 on 2025-05-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='current_progress',
            field=models.FloatField(default=0),
        ),
    ]
