# Generated by Django 5.2 on 2025-11-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_current_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userchallenge',
            options={'ordering': ['-joined_date']},
        ),
    ]
